### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [audiomancer/react-domless-media#2]
Greetings, @audiomancer 

I wanted to collaborate with this project
by delivering a _free_ logo proposal,
If that's something you're interested in let me know!

I'm a Graphic Designer and an Open Source Enthusiast!
Cheers!
-Luigi.

**Comment by audiomancer** [comment]
Great, some logo would be nice! Graphic design is not my strongest suit, so it's all up to you how will it look like :)

**Comment by LuigiBaute** [comment]
Thanks I'll start working on it, I've noticed this project doesn't have a license, it doesn't have one? or you havent upload it yet? 

Cheers!

**Comment by nickserv** [comment]
MIT: https://github.com/audiomancer/react-domless-media/blob/master/package.json#L36
https://opensource.org/licenses/MIT

**Comment by LuigiBaute** [comment]
Greetings @audiomancer The name of the project is domless? would you clarify that for me? thanks! I'm working on the design already.

**Comment by audiomancer** [comment]
Hello! Full name of this project is react domless media, and the core concept is described in readme.md

> It is not creating any DOM nodes on its own, thus it does not disturb already existing styling. [...] Instead of creating its own DOM node and applying css styles to it, it applies them to all immediate DOM nodes of all provided children, if they have any.

You can refer to this idea somehow, if you want.

**Comment by LuigiBaute** [comment]
Hello! @audiomancer I wanted to deliver a simple and understandable logo concept that goes along with the project, any suggestions? I'll gladly adjust anything as many times as necessary. I hope you like it!
![logotipo react domless media](https://user-images.githubusercontent.com/36426974/40092680-90cfedf6-588c-11e8-953c-49337b011e8a.jpg)

**Comment by audiomancer** [comment]
I like the eye option more. What exactly does it represents? It should be interpreted somehow, or it's just a logo?

**Comment by LuigiBaute** [comment]
I wanted to go for ''web designer-ish kind of thing'' , But basically it's a simple and unique logo that I think suits the project, what do you think? @audiomancer Should I submit a pull request?

**Comment by audiomancer** [comment]
This circle gave me an idea of some other logo too, which directly presents the idea of this project. What about circle with something very similar to this https://www.iconfinder.com/icons/2317371/bynary_data_hierarchy_nodes_structure_tree_icon#size=512 (I like diagonals) inside it. All circles in this tree should be full excepting one empty, which would represent this component. How about that?

**Comment by LuigiBaute** [comment]
Ok so let me see if I understood, The ''web'' circle with that image pattern inside of it? @audiomancer

**Comment by audiomancer** [comment]
Oh, I've got an idea! Look at this https://cdn-images-1.medium.com/max/312/1*SRL22ADht1NU4LXUeU4YVg.png . This is redux logo, it is referring to the atom symbol, which is the logo of React.js. If you could somehow combine that https://www.iconfinder.com/icons/2317371/bynary_data_hierarchy_nodes_structure_tree_icon#size=512 with atom orbitals, it would be imo the perfect logo, very easy to understand and just by looking at it, people would know that it's something connected with react.

**Comment by LuigiBaute** [comment]
Ok @audiomancer :) thats good, Ill come up with something as soon as posible, thanks!

**Comment by audiomancer** [comment]
:)

**Comment by LuigiBaute** [comment]
Hello @audiomancer this is what I came up with,

Using the given suggestion I was able to unify both elements so I could came up with at atom with the binary code inside of it, This is the demostration of the project in several colors for you to choose the one you like the most, or if you have any color in mind I can use that, I hope you like it.

-Luigi 


![logotipo react domless media segunda propuesta](https://user-images.githubusercontent.com/36426974/40153130-34de6642-5956-11e8-99a2-4956fae42180.jpg)

**Comment by nickserv** [comment]
These logos look more complex, but I really like the flat design, colors, and style of the bottom two.

**Comment by audiomancer** [comment]
Sorry for not responding yesterday, but I had a fever, sore throat and I was mostly laying in bed :( . Dang... this is too complex. I think dom tree can't be combined with orbitals though, it looks unnatural, it was a bad idea, my bad. I think the only sensible option is something like this 
![logo propsal](https://user-images.githubusercontent.com/39003780/40230518-19283638-5a98-11e8-963c-62c9470bd3dd.jpg)
It's slightly referring to react by hexagonal background, and this rectangle with RDM is transparent, so it shows what's this component about, yet it's simple enough to be near infinitely scalable, so it would be looking good even in tiny sizes.

**Comment by LuigiBaute** [comment]
Oh, don't worry about it mate @audiomancer ,
I can definitely do that, I'll submit it later today when it's ready, ok!
Feel better!

**Comment by LuigiBaute** [comment]
Hey again! @audiomancer ,
I hope you like these ones,
they can be in any colour you like.
![logotipo react domless media](https://user-images.githubusercontent.com/36426974/40283597-c1ccef92-5c4e-11e8-9dce-80dc167a8b7b.jpg)

**Comment by audiomancer** [comment]
Now everything is on track. Could you re-make the left column with the RDM rectangles which are always empty like in the bottom one and show these three?

**Comment by LuigiBaute** [comment]
That's what I tried to create with the 1st and 2nd logo from the right column @audiomancer making them hollow is the only way I saw I could add up some colour background to it :+1:

**Comment by LuigiBaute** [comment]
The only way I can make them look empty is by adding a third color. @audiomancer 
and it could end up looking too crowded again or messy
that's why I sticked with the ''hollow'' rectangle to difference it from the 'rdm' rectangle

**Comment by audiomancer** [comment]
Hello @LuigiBaute :) I mean, could you make hollow only the rectangles with "RDM" and leave the small ones full as their are in this two upper logos from left column?

**Comment by LuigiBaute** [comment]
Ok ok. I understand, I'll upload when ready ok? @audiomancer

**Comment by audiomancer** [comment]
Cool

**Comment by LuigiBaute** [comment]
Hey @audiomancer ,
I hope you like these ones!
![logotipo react domless media 3](https://user-images.githubusercontent.com/36426974/40339021-48cad1c4-5d46-11e8-8dc4-f69e18f095e2.jpg)

**Comment by audiomancer** [comment]
Ok, after comparing all versions I think this one is the best 
![six](https://user-images.githubusercontent.com/39003780/40365662-5cfe9862-5dd5-11e8-9a3e-7d48e2267060.jpg)
Simple, scalable and good loking. But it should be refined a little bit. Could you arrange this small rectangles to the sides of the big one like in other versions? This indentation looks weird imo.

**Comment by LuigiBaute** [comment]
Ok! Ill show you the final result and then create a pull request! 
@audiomancer

**Comment by LuigiBaute** [comment]
Hey! @audiomancer 
This would be the final result. :+1: 
 
![logotipo react domless media arte final](https://user-images.githubusercontent.com/36426974/40446097-12804976-5e9c-11e8-89bf-b08ba002db76.jpg)

**Comment by LuigiBaute** [comment]
Hey! @audiomancer This would be the final result, 

thanks for letting me be a part of this cool project!

![logotipo react domless media png](https://user-images.githubusercontent.com/36426974/40447418-7c20e9a4-5ea0-11e8-8023-49edd716da68.png)

**Comment by audiomancer** [comment]
Yeah, this looks serious. I see, that these small nodes are rectangles instead of being squares. Is it purposeful? I do not know much about the composition and placement of elements.

**Comment by LuigiBaute** [comment]
I made them _rectangles_ because I wanted to make them the same shape of the _RDM rectangle_ and they also look better inside the hexagonal background
@audiomancer

**Comment by audiomancer** [comment]
Ok, last thing before commit: could You please make 8-10 different color versions of it and show how they would look like :) ?

**Comment by LuigiBaute** [comment]
![1](https://user-images.githubusercontent.com/36426974/40455472-0ff22e76-5ebb-11e8-9d76-46b2cefbfa95.png)

Here are 9 different colors for you to choose from @audiomancer

**Comment by audiomancer** [comment]
Could Youl please make one more with #61DBFB ?

**Comment by LuigiBaute** [comment]
Done! @audiomancer 
![2](https://user-images.githubusercontent.com/36426974/40456300-a39af808-5ebe-11e8-8ed6-ebb6bb1ac556.png)

**Comment by audiomancer** [comment]
Ok, and the last two - could You please make the gradient as it is here?
![gradients](https://user-images.githubusercontent.com/39003780/40456414-96339278-5ef1-11e8-8c29-210723a41327.jpg)
I think it may looks better than solid color.

**Comment by LuigiBaute** [comment]
I hope you like these, I did :+1:  @audiomancer 
![logotyperdm3](https://user-images.githubusercontent.com/36426974/40456844-6827d338-5ec1-11e8-87d9-3f78cf96adea.png)

**Comment by audiomancer** [comment]
Could You please turn this gradient at this left propsal upside-down exactly like it is at this eye?

**Comment by LuigiBaute** [comment]
:+1: @audiomancer 
![dfjdf](https://user-images.githubusercontent.com/36426974/40457043-5a40754e-5ec2-11e8-85ce-dca60a1197c1.png)

**Comment by audiomancer** [comment]
I think I like this more though.
![grad](https://user-images.githubusercontent.com/39003780/40457341-3d11942e-5ef6-11e8-8fe4-1902c6cadeaa.png)
You can pull!
Welcome in team ;)

**Comment by LuigiBaute** [comment]
Ok Ill submit the commit and hand you the google drive links with the monochromatic versions for any future updates, and thank you :+1: 

@audiomancer it has been a pleasure!

best regards.

**Comment by audiomancer** [comment]
@LuigiBaute as it was for me!

Regards and thanks for killer logo 👌

**Comment by LuigiBaute** [comment]
I've submitted the pull request now @audiomancer :100:
